import { Idea, RankedIdea } from "@/lib/types";
import { sortIdeasByRank } from "@/lib/scoring";

const rawIdeas: Idea[] = [
  {
    title: "Access Wiki",
    slug: "access-wiki",
    category: "Infrastructure / Access",
    description:
      "A structured knowledge layer for permissions, access rules, tokenized entry logic, and spatial coordination.",
    painSeverity: 9,
    frequency: 8,
    marketSize: 9,
    monetizationClarity: 8,
    dataAvailability: 6,
    defensibility: 9,
    networkEffects: 8,
    automationPotential: 8,
    founderFit: 9,
    strategicLeverage: 10,
    regulatoryRisk: 4,
    buildSimplicity: 5,
    retentionPotential: 8,
    narrativePower: 9,
    expansionSurface: 10,
    urgencyScore: 8,
    buildabilityScore: 6,
    founderAdvantageScore: 9,
    confidenceScore: 8,
    bucket: "BUILD FIRST",
    rationale:
      "Strong long-term platform potential with a deep infrastructure moat, API upside, and strategic leverage across multiple future products.",
    risks: [
      "Data collection is harder early on",
      "Category education may be required",
      "MVP scope can expand too quickly",
    ],
    recommendedAction:
      "Build a focused MVP around access logic, permission layers, and structured venue or building rules.",
  },
  {
    title: "Operator Wiki",
    slug: "operator-wiki",
    category: "Operations / Real-World Knowledge",
    description:
      "A real-world execution wiki for costs, timelines, inspections, sequencing, and operational playbooks.",
    painSeverity: 9,
    frequency: 9,
    marketSize: 8,
    monetizationClarity: 9,
    dataAvailability: 8,
    defensibility: 7,
    networkEffects: 7,
    automationPotential: 8,
    founderFit: 10,
    strategicLeverage: 9,
    regulatoryRisk: 3,
    buildSimplicity: 8,
    retentionPotential: 8,
    narrativePower: 7,
    expansionSurface: 8,
    urgencyScore: 9,
    buildabilityScore: 9,
    founderAdvantageScore: 10,
    confidenceScore: 9,
    bucket: "BUILD FIRST",
    rationale:
      "Clear pain, immediate monetization, strong founder fit, and faster time-to-market than more abstract infrastructure plays.",
    risks: [
      "Can look niche if positioned too narrowly",
      "Need clean taxonomy for structured knowledge",
      "Must avoid turning into generic blog content",
    ],
    recommendedAction:
      "Build first as a fast cash-flow and authority product while Access Wiki develops as the deeper platform layer.",
  },
  {
    title: "Legal Navigation Wiki",
    slug: "legal-navigation-wiki",
    category: "Legal / System Navigation",
    description:
      "A structured navigation system for legal processes, procedural steps, timelines, outcomes, and decision support.",
    painSeverity: 9,
    frequency: 7,
    marketSize: 9,
    monetizationClarity: 8,
    dataAvailability: 7,
    defensibility: 7,
    networkEffects: 6,
    automationPotential: 8,
    founderFit: 7,
    strategicLeverage: 8,
    regulatoryRisk: 7,
    buildSimplicity: 6,
    retentionPotential: 7,
    narrativePower: 8,
    expansionSurface: 8,
    urgencyScore: 8,
    buildabilityScore: 6,
    founderAdvantageScore: 7,
    confidenceScore: 7,
    bucket: "HIGH PRIORITY",
    rationale:
      "Very strong pain and monetization potential, but trust, liability, and compliance pressure increase execution complexity.",
    risks: [
      "Accuracy burden is high",
      "Legal sensitivity can slow expansion",
      "May need careful disclaimers and review flows",
    ],
    recommendedAction:
      "Generate build pack now, but position as navigation and procedural intelligence rather than legal advice.",
  },
  {
    title: "City Intelligence Wiki",
    slug: "city-intelligence-wiki",
    category: "Local Intelligence",
    description:
      "A live city-layer for crime, rent, foot traffic, events, transit, price shifts, and neighborhood intelligence.",
    painSeverity: 7,
    frequency: 8,
    marketSize: 8,
    monetizationClarity: 7,
    dataAvailability: 8,
    defensibility: 6,
    networkEffects: 7,
    automationPotential: 9,
    founderFit: 6,
    strategicLeverage: 7,
    regulatoryRisk: 3,
    buildSimplicity: 7,
    retentionPotential: 7,
    narrativePower: 8,
    expansionSurface: 8,
    urgencyScore: 8,
    buildabilityScore: 8,
    founderAdvantageScore: 6,
    confidenceScore: 8,
    bucket: "HIGH PRIORITY",
    rationale:
      "Good breadth and visual appeal with strong repeat use cases, but harder to differentiate without a sharp wedge.",
    risks: [
      "Can become noisy fast",
      "Needs a narrow wedge to win",
      "Many fragmented substitutes exist",
    ],
    recommendedAction:
      "Keep in the high-priority queue and test with one city and one wedge before broad expansion.",
  },
  {
    title: "Skill Graph Wiki",
    slug: "skill-graph-wiki",
    category: "Education / Hiring",
    description:
      "A structured map of skills, subskills, paths, and outcome-linked learning and hiring intelligence.",
    painSeverity: 7,
    frequency: 7,
    marketSize: 8,
    monetizationClarity: 7,
    dataAvailability: 7,
    defensibility: 6,
    networkEffects: 7,
    automationPotential: 8,
    founderFit: 6,
    strategicLeverage: 7,
    regulatoryRisk: 2,
    buildSimplicity: 7,
    retentionPotential: 7,
    narrativePower: 7,
    expansionSurface: 8,
    urgencyScore: 7,
    buildabilityScore: 8,
    founderAdvantageScore: 6,
    confidenceScore: 7,
    bucket: "BACKLOG",
    rationale:
      "Broad market and useful knowledge graph concept, but competition is heavier and wedge clarity matters.",
    risks: [
      "Crowded market",
      "Must prove differentiation fast",
      "Could drift into generic education tooling",
    ],
    recommendedAction:
      "Backlog unless paired with a sharper industry-specific wedge.",
  },
  {
    title: "Experience Wiki",
    slug: "experience-wiki",
    category: "Lifestyle / Experience Intelligence",
    description:
      "A structured system for what places, events, and experiences actually feel like beyond shallow reviews.",
    painSeverity: 6,
    frequency: 7,
    marketSize: 7,
    monetizationClarity: 6,
    dataAvailability: 7,
    defensibility: 5,
    networkEffects: 8,
    automationPotential: 7,
    founderFit: 6,
    strategicLeverage: 6,
    regulatoryRisk: 3,
    buildSimplicity: 8,
    retentionPotential: 7,
    narrativePower: 8,
    expansionSurface: 7,
    urgencyScore: 7,
    buildabilityScore: 8,
    founderAdvantageScore: 6,
    confidenceScore: 7,
    bucket: "BACKLOG",
    rationale:
      "Fresh angle and socially engaging, but monetization is softer and structured trust is harder to establish.",
    risks: [
      "Data quality and consistency can vary",
      "Monetization less direct",
      "May resemble review platforms unless differentiated clearly",
    ],
    recommendedAction:
      "Backlog or bundle later into a broader city or lifestyle intelligence system.",
  },
];

export const ideas: RankedIdea[] = sortIdeasByRank(rawIdeas);
