export type VentureIdeaRow = {
  id: string;
  title: string;
  slug: string;
  category: string;
  description: string;
  pain_severity: number;
  frequency: number;
  market_size: number;
  monetization_clarity: number;
  data_availability: number;
  defensibility: number;
  network_effects: number;
  automation_potential: number;
  founder_fit: number;
  strategic_leverage: number;
  regulatory_risk: number;
  build_simplicity: number;
  retention_potential: number;
  narrative_power: number;
  expansion_surface: number;
  urgency_score: number;
  buildability_score: number;
  founder_advantage_score: number;
  confidence_score: number;
  bucket: string;
  rationale: string;
  risks: string[] | unknown;
  recommended_action: string;
  created_at: string;
  updated_at?: string;
};

export type SpawnPack = {
  productThesis: string;
  icp: string[];
  mvpFeatures: string[];
  monetizationStrategy: string[];
  gtmStrategy: string[];
  expansionRoadmap: string[];
};

export type IdeaStatus = 'active' | 'paused' | 'archived';

export type RankedIdeaView = {
  id?: string;
  title: string;
  slug: string;
  category: string;
  description: string;
  status: IdeaStatus;
  painSeverity: number;
  frequency: number;
  marketSize: number;
  monetizationClarity: number;
  dataAvailability: number;
  defensibility: number;
  networkEffects: number;
  automationPotential: number;
  founderFit: number;
  strategicLeverage: number;
  regulatoryRisk: number;
  buildSimplicity: number;
  retentionPotential: number;
  narrativePower: number;
  expansionSurface: number;
  urgencyScore: number;
  buildabilityScore: number;
  founderAdvantageScore: number;
  confidenceScore: number;
  bucket: "BUILD FIRST" | "HIGH PRIORITY" | "BACKLOG" | "IGNORE / MERGE";
  rationale: string;
  risks: string[];
  recommendedAction: string;
  priorityScore: number;
  masterRankScore: number;
  confidenceAdjustedScore: number;
};
